version: '3.8'

services:
  backend:
    # image: trungnghia1996/go-fiber-api:latest
    build: .
    container_name: go-fiber-api
    ports:
      - 4000:4000
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable
      JWT_SECRET: test
      JWT_SECRET_ADMIN: testadmin
      PORT: 4000
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
